name: Scrape Bluestar

on:
  schedule:
    # Run exactly at 01:30 AM America/New_York (EDT right now -> 05:30 UTC) for testing
    - cron: '30 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # No time gate; schedule is precise

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and OS deps
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          MEDSTAT_EMAIL: ${{ secrets.MEDSTAT_EMAIL }}
          MEDSTAT_PASSWORD: ${{ secrets.MEDSTAT_PASSWORD }}
        run: npx playwright test tests/bluestar_all.spec.ts --project=chromium

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bluestar-data
          path: |
            data/products_all.xlsx
            data/products_all.json
            data/product_urls_all.json
          if-no-files-found: warn

      - name: Commit and push updated data to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/products_all.xlsx data/products_all.json data/product_urls_all.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: automated scrape [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

